version: 2

models:
  - name: dim_planets
    description: >
      Dimension with all exoplanets
    columns:
      - name: planet_id
        description: UUID for a planet
        tests:
            - not_null:
                severity: error
      - name: planet_name
        description: Common name for the planet
        tests:
            - not_null:
                severity: error
  - name: dim_stars
    description: >
      Dimension with all host starts
    columns:
      - name: star_id
        description: UUID for a star
        tests:
            - not_null:
                severity: error
      - name: star_name
        description: Common name for the planet
        tests:
            - not_null:
                severity: error